YLP-561 messaging when a team invites a patient
mdblp/hydrophone pull request #130
Opened 2021-03-23 07:27 UTC by franck-fourel

- [x] message template
- [ ] integrate API calls
- [ ] integrate Crew

2021-04-07 14:24 UTC, ydrisR requested changes
Questions about re-use of existing code and api route.
One change required about perms.AddMember

2021-04-07 14:24 UTC, ydrisR commented on api/hydrophoneApi.go
> +	send.Handle("/team/invite/patient", varsHandler(a.SendTeamInvitePatient)).Methods("POST")
Why not use the same route for patients and members? `/team/invite` ?

2021-04-07 14:24 UTC, ydrisR commented on api/invite.go
> +func (a *Api) SendTeamInvitePatient(res http.ResponseWriter, req *http.Request, vars map[string]string) {
This function is almost a copy of SendTeamInvite. The only difference is the template type/name and the authorization logic.
Can we reuse the same function or at least factorize?

2021-04-07 14:24 UTC, ydrisR commented on api/invite.go
> +		if _, err := a.perms.AddTeamMember(tokenValue, member); err != nil {
This should not work... AddTeamMember works for admin and medical member only, not for patients

2021-04-09 11:05 UTC, franck-fourel commented
the 2 routes to add members and patients have been merged
To do: the patients are not added into a team as the crew client was not yet available. It will be done shortly.

2021-04-12 09:19 UTC, ydrisR approved these changes
Not complete, but ok to merge.

2021-04-12 09:19 UTC, merged