YLP-705 Hydrophone should consider caregivers as clinical accounts on pin-reset/forgot-emails and signup
mdblp/hydrophone pull request #136
Opened 2021-04-27 10:00 UTC by CedricPerotto

+ Using shoreline client from mdblp/shoreline (instead of go-common).

2021-04-28 07:26 UTC, ydrisR requested changes
a few suggetions, we can discuss as I'm not sure what is best :)

2021-04-28 07:26 UTC, ydrisR commented on api/forgot.go
> +		if resetUsr.IsClinic() || resetUsr.HasRole("caregiver") || a.Config.AllowPatientResetPassword {
OR something like `!resetUsr.HasRole("patient") || a.Config.AllowPatientResetPassword` ?

2021-04-28 07:26 UTC, ydrisR commented on api/pin_reset.go
> +	if usrDetails.IsClinic() || usrDetails.HasRole("caregiver") {
```suggestion
	if !usrDetails.HasRole("patient") {
```

2021-04-28 07:26 UTC, ydrisR commented on api/signup.go
> +		if usrDetails.IsClinic() || usrDetails.HasRole("caregiver") {
```suggestion
		if !usrDetails.HasRole("patient") {
```

2021-04-28 07:26 UTC, ydrisR commented on CHANGELOG.md
> +## 1.6.0
1.6.1? And need a date

2021-04-28 08:05 UTC, CedricPerotto commented on CHANGELOG.md
> +## 1.6.0
> 1.6.1? And need a date

Version 1.6.0 wasn't released

2021-05-03 08:12 UTC, ydrisR approved these changes

2021-05-03 13:57 UTC, merged