Feature/ylp 710 accept generic notifications bis
mdblp/hydrophone pull request #143
Opened 2021-05-04 13:50 UTC by ydrisR

Merge accept invite routes for teams. No need to have 2 dinstinct routes

2021-05-04 16:27 UTC, CedricPerotto requested changes

2021-05-04 16:27 UTC, CedricPerotto commented on api/invite_test.go
> +			url:      fmt.Sprintf("/accept/team/invite"),
No need to use Sprintf without variables (I didn't suggest all other usage). 
```suggestion
			url:      "/accept/team/invite",
```

2021-05-04 16:27 UTC, CedricPerotto commented on api/invite.go
> +		ValidateUserID(inviteeID, &validationErrors)
We don't have to validate teamID any more ? 
( `ValidateTeamID(teamID, &validationErrors)` has been removed).

In that case ValidateTeamID method is not used anywhere.

2021-05-04 16:27 UTC, CedricPerotto commented on api/invite.go
> +		a.acceptTeamInvite(res, req, conf)
I think we can use a case list in go 
```suggestion
	case models.TypeMedicalTeamPatientInvite, models.TypeMedicalTeamInvite :
		a.acceptTeamInvite(res, req, conf)
```

2021-05-04 16:27 UTC, CedricPerotto commented on api/invite.go
> +// @Description  Send an email and a notification to the new admin user. The role change is done but notification is pushed for information (notifacation status is set to pending). Removing the admin
```suggestion
// @Description  Send an email and a notification to the new admin user. The role change is done but notification is pushed for information (notification status is set to pending). Removing the admin role is managed as an exception. It does not trigger any notification or email.
```

2021-05-04 17:06 UTC, franck-fourel requested changes
couple of comments

2021-05-04 17:06 UTC, franck-fourel commented on api/invite.go
> +// @ID hydrophone-api-acceptAnyInvite
```suggestion
// @ID hydrophone-api-acceptTeamNotifs
```

2021-05-04 17:06 UTC, franck-fourel commented on api/invite_test.go
> +			url:      fmt.Sprintf("/accept/team/invite"),
```suggestion
			url:      "/accept/team/invite",
```

2021-05-04 17:06 UTC, franck-fourel commented on api/invite_test.go
> +			url:      fmt.Sprintf("/accept/team/invite"),
```suggestion
			url:      "/accept/team/invite",
```

2021-05-04 17:06 UTC, franck-fourel commented on api/invite_test.go
> +			url:      fmt.Sprintf("/accept/team/invite"),
```suggestion
			url:      "/accept/team/invite",
```

2021-05-04 17:06 UTC, franck-fourel commented on api/invite_test.go
> +			url:      fmt.Sprintf("/accept/team/invite"),
```suggestion
			url:      "/accept/team/invite",
```

2021-05-04 17:06 UTC, franck-fourel commented on api/invite_test.go
> +			url:      fmt.Sprintf("/accept/team/invite"),
```suggestion
			url:      "/accept/team/invite",
```

2021-05-04 18:31 UTC, ydrisR commented on api/invite.go
> +		a.acceptTeamInvite(res, req, conf)
cool :+1:

2021-05-05 09:08 UTC, CedricPerotto commented on api/invite.go
> +		ValidateUserID(inviteeID, &validationErrors)
My point was also that we don't check anymore that conf.TeamID is not nil (or accept.TeamID not sure if we have to check that in the payload or in the db response).

2021-05-05 12:06 UTC, CedricPerotto approved these changes

2021-05-05 12:06 UTC, merged