YLP-743 A patient team invitation requires that the patient account already exists
mdblp/hydrophone pull request #146
Opened 2021-05-07 14:40 UTC by franck-fourel

2021-05-10 10:05 UTC, Nas84 requested changes

2021-05-10 10:05 UTC, Nas84 commented on api/invite_test.go
> +		// {
Why the test are commented ?

2021-05-10 14:49 UTC, franck-fourel commented on api/invite_test.go
> +		// {
reverted

2021-05-11 12:16 UTC, Nas84 approved these changes
looks good to me

2021-05-11 12:58 UTC, franck-fourel commented
> looks good to me (of course require the jenkins tests to pass)

can you have a look. 
the failing test was coming from a bad rebase

2021-05-11 13:01 UTC, merged