YLP-1428 invite monitoring patient
mdblp/hydrophone pull request #191
Opened 2022-04-19 05:49 UTC by franck-fourel

- add routes to manage invite/accept/dismiss monitoring patient
 - dependency on https://github.com/mdblp/crew/pull/36 so that crew client is updated with new minitoring features
 - little go dependencies update (there is one one to please testify that Im'n not sure to understand)

Still open questions on what we should do when a monitoring request is cancelled by a HCP: should we inform the patient. The current solution does not make any emails to the patient.

2022-05-06 14:54 UTC, CedricPerotto reviewed
See my comments as already discussed build.sh + **templates/preview/build.sh (for hydromail)** need to be updated with 
`go mod tidy -compat=1.17`

2022-05-06 14:54 UTC, CedricPerotto commented on api/invite.go
> +	if team.ID == "" {
I think we should also check that
1. The current user is an admin of the team (As only admins can dismiss invites...)
2. The current team is a monitored team

2022-05-06 14:54 UTC, CedricPerotto commented on api/invite_test.go
> +		// Role:             "patient",
```suggestion
```

2022-05-06 14:54 UTC, CedricPerotto commented on templates/html/medicalteam_monitoring_invitation.html
> +                      <a class="btn primary" href="{{.WebURL}}/{{ .WebPath }}?inviteEmail={{ .Email }}" style="text-decoration:none;display:inline-block;font-family:'Ubuntu', sans-serif;border-radius
I can't see this inviteEmail={{ .Email }} query parameter in blip code source

2022-05-06 15:53 UTC, CedricPerotto requested changes
Another global comment the `GetReceivedInvitations` API method (and maybe `GetSentInvitations`) should be updated to include TypeMedicalTeamMonitoringInvite types when role is patient (role is not used in `GetSentInvitations`).

2022-05-10 09:34 UTC, ydrisR approved these changes
LGTM

2022-05-10 09:35 UTC, merged