YLP-1737: new object "notification"
mdblp/hydrophone pull request #209
Opened 2022-09-14 17:11 UTC by ydrisR

New generic route "/notifications" to process various topics

2022-09-21 16:47 UTC, ydrisR commented
Depends on seagull client: https://github.com/mdblp/seagull/pull/37

2022-09-26 15:57 UTC, CedricPerotto requested changes
Durign my tests, the email sent didn't include the secret code and the duration of the invite

2022-09-26 15:57 UTC, CedricPerotto commented on api/forgot_test.go
> +		mockSeagull.On("GetCollections", "expires@myemail.com", []string{"preferences"}).Return(&schema.SeagullDocument{}, nil)
We never test a seagull response with a custom language preference ?

2022-09-26 15:57 UTC, CedricPerotto commented on templates/locales/en.yaml
> +AppPrescriptionBody2: "To accept, blablabla, click on the link below."
blablabla ?

2022-10-04 07:12 UTC, CedricPerotto commented on api/hydrophoneApi.go
> +
Do we still need this type and this const (it's in go-routers now) ?

2022-10-04 07:12 UTC, CedricPerotto commented on api/notification.go
> +	if a.createAndSendNotification(req, invite, content, inviteeLanguage) {
invite (models.Confirmation) as a creator.profile field which is not set here, it could be interesting to store it in the invite (as we retrieve the profile just before...) .

2022-10-04 07:12 UTC, CedricPerotto commented on models/confirmation.go
>  )
on the following line, I think there is a Timeout missing for the new "TypeNotification" (or maybe we shoud handle duration differently for notifications... but for now it is set to 0 days with the app_prescription).

2022-10-04 13:50 UTC, CedricPerotto approved these changes

2022-10-04 13:50 UTC, merged