PT-636 Feature/add config check route
mdblp/hydrophone pull request #60
Opened 2019-09-13 15:34 UTC by BigFab

I added new route for sanity check email sending

System tests were added. I leveraged what is done today in hydrophone for system tests. This could be done better, especially the shoreline mock that is not able to deal with wrong tokens (only present/absent).

2019-09-17 14:23 UTC, yvon-dblg requested changes

2019-09-17 14:23 UTC, yvon-dblg commented on docs/README.md
> +## /inform
```suggestion
## POST /inform
```

2019-09-17 14:23 UTC, yvon-dblg commented on docs/README.md
> +## /sanity_check
```suggestion
## POST /sanity_check
```

2019-09-17 14:23 UTC, yvon-dblg commented on api/verify.go
> +	var subject string = "Sanity Check Email"
```suggestion
	subject := "Sanity Check Email"
```

2019-09-17 14:23 UTC, yvon-dblg commented on api/verify.go
> +	var recipient string = a.Config.TestEmail
```suggestion
	recipient := a.Config.TestEmail
```

2019-09-17 14:23 UTC, yvon-dblg commented on api/verify.go
> +	var body string = "This is an automatic email sent from Hydrophone service to prove all configuration is in place for sending emails"
```suggestion
	body := "This is an automatic email sent from Hydrophone service to prove all configuration is in place for sending emails"
```

2019-09-19 19:06 UTC, ydrisR commented
@BigFab would be nice if the destination email was the email of the account corresponding to the token provided. i.e. we setup a test account (with our own email address) to execute this test during deployment. 
This would avoid spam, otherwise a user with a valid account could repeatidly call these route and send us thousands of email...

2019-09-19 19:06 UTC, ydrisR requested changes
@BigFab would be nice if the destination email was the email of the account corresponding to the token provided. i.e. we setup a test account (with our own email address) to execute this test during deployment.
This would avoid spam, otherwise a user with a valid account could repeatidly call these route and send us thousands of email...

2019-09-24 09:25 UTC, BigFab commented
I reviewed the code to include your comments @yvon-dblg 
I also reviewed the code to make your suggestion a reality @ydrisR 
I finally reviewed the tests to accomodate new logic

2019-09-24 12:43 UTC, yvon-dblg requested changes
- Need to be rebase from the dblp branch
- Error while testing in postman using the `portal.admin@diabeloop.fr` account
```
2019/09/24 12:26:22 Sanity check email route
2019/09/24 12:26:22 Found token in request header eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkdXIiOjI1OTIwMDAsImV4cCI6MTU3MTkxOTk3MSwic3ZyIjoibm8iLCJ1c3IiOiJlNmE5MjRiOTg4In0.GbyL0GQazv5II8_2GTJKDy3p7C5T8oL55pwxLPRb6jU
2019/09/24 12:26:23 Issue sending sanity check email: Status [500] Message [: 
	status code: 404, request id: ]
```

2019-09-24 14:41 UTC, yvon-dblg approved these changes

2019-09-24 15:54 UTC, ydrisR reviewed
Any reason to change the configuration file? (env.sh). It makes one more difference with tidepool origin...

2019-09-25 14:18 UTC, BigFab commented
@ydrisR so about env.sh, do you mean we should not modify at all? This configuration file is not used by our stack, right?

2019-09-25 14:35 UTC, BigFab commented
@ydrisR I did cancel the changes in the env.sh

2019-09-25 18:49 UTC, ydrisR approved these changes

2019-09-25 18:56 UTC, merged