[PT-671] Update the status endpoint to display the version number
mdblp/hydrophone pull request #64
Opened 2019-10-14 15:43 UTC by ydrisR

Use the features from go-common to display the version number on the status route.
Now the status object (from go-common) is always used, no matter whether the status is OK or NOK.

The variables `ReleaseNumber` and `FullCommit` have to be injected at build time using:
`go build -ldflags '-X main.ReleaseNumber=1.0.5 -X main.FullCommit=123456789bla'`

2019-10-15 08:38 UTC, ydrisR commented
**WARNING** do not merge the PR as is. I changed the toml file to reference the relevant branche in go-common ( `feature/PT-727_Enhance_Status_Report`) instead of master.

2019-10-15 08:54 UTC, ydrisR commented
Another detail to validate: the status object {code, reason, error, version} is not used for the status url only. It is returned in all error responses by hydrophone (see the last commit to fix signup tests).  
I don't think it is a problem to add the version in these error responses but I'd like a second opinion.

2019-10-17 14:16 UTC, BigFab reviewed
LGTM although I would have taken the release version number from the CHANGELOG instead of Github

Tests were OK on my side. I tested by running a build.sh then through the docker container. I got the release number I was expecting i.e. retrieved from the git repository

I am waiting for the final commit (to include the "released" go-common lib) before retesting/approving/merging

Good job @ydrisR @CedricPerotto !

2019-10-17 14:16 UTC, BigFab commented on Dockerfile
> -RUN  dos2unix build.sh && ./build.sh && \
so we assume we won't have need for "dos2unix" anymore?

2019-10-17 16:25 UTC, ydrisR commented on Dockerfile
> -RUN  dos2unix build.sh && ./build.sh && \
good question... I hope we won't since we know where the problem was comming from ;)

2019-10-18 10:11 UTC, BigFab requested changes

2019-10-18 10:11 UTC, BigFab commented on build.sh
> +go build -ldflags "-X $GO_COMMON_PATH/clients/version.ReleaseNumber=$VERSION_BASE \
Looks like a good practice to run "go mod tidy" to prune the dependencies before building. Does it make sense?
https://github.com/golang/go/wiki/Modules#how-to-prepare-for-a-release

2019-10-18 10:11 UTC, BigFab commented on build.sh
> +go build -ldflags "-X $GO_COMMON_PATH/clients/version.ReleaseNumber=$VERSION_BASE \
```suggestion
go mod tidy
go build -ldflags "-X $GO_COMMON_PATH/clients/version.ReleaseNumber=$VERSION_BASE \
```

2019-10-18 14:41 UTC, BigFab approved these changes
LGTM

2019-10-18 14:45 UTC, merged